### ISSUE TITLE
define UID:GID of kallithea-user

### ISSUE THREAD

**Issue by SvenRoederer** [toras9000/docker-kallithea#2]
I use a setup where the repo folder is mapped to regulare filesystem-location via bind-mount.  To not clash with host UID 1000 an option to specify the UID and GID would be great.
This will avoid hacking around to change the IDs.

I can PR this, will you merge?

**Comment by toras9000** [comment]
@SvenRoederer 
Thank you for your suggestions.

I basically used it only for personal management and wasn't really aware of it.
I am not familiar with user management, so it is helpful to hear such an opinion.

I reset commits often so that a single changeset in this repository is tied to an image tag.
This is also the reason why commits per version are handled in branches instead of tags.
I appreciate the PR suggestions, but it may be problematic to accept them in the same way as general OSS.

So I just tried adding one [commit](https://github.com/toras9000/docker-kallithea/commit/0bdef62c72a885458a75f21ec69ccc9a455f687e) myself, is this what you meant?
However, the way this image is created does not seem very appropriate for making this change.
In this image, kallithea is currently installed under the user's home directory, which will result in many ownership changes when the UID is changed.
Perhaps we should reconsider starting with the installation process?
It may be better to create a different Dockerfile.

I would be glad to learn from your knowledge.

**Comment by SvenRoederer** [comment]
My initial idea did not include  changing the permissions of existing repos, but only setting the container-user to any specified ID (assuming the sysop has correctly setup the host-folder permissions). So that the 2nd part of your change can be reduced.

I also see the downside of changing the UID/GID at container-creation time. I also like the idea of running the processes with non-root, as it adds another layer of security along docker itself.

**Comment by toras9000** [comment]
Thank you.
Yes, changing repository permissions can be done either way. For startup scripts, it may not be necessary.

I did not indicate in detail in my previous comment, but the issue is the UID change.
The current image takes a very long time to process the following.
This appears to increase container startup time by a factor of 20 to 30. And every time.
```
usermod  -o -u "$KALLITHEA_UID" kallithea
```

I think it would be useful to run the process as a specific user and is necessary for SSH protocol support.
However, I doubt that pip install with `--user` in the Dockerfile is necessary.
I don't remember why I did this at the time. Was this necessary?
Now I am thinking that we can just run kallithea installed by root as a different user.
Therefore, we will need to try to see if we can optimize the construction method more.

**Comment by SvenRoederer** [comment]
Yeah, the "install pip as root, but run app as user" I have seen also as an potential optimisation. But I was not willing to mix it into this issue here.

For sure chown-ing the files takes some time, but for the moment I would be fine with that and address as separate change (splitting pip install uid, adding some find-magic, ...). Also only touching the repo-hierarchy owner I would rely on ```KALLITHEA_FIX_REPOS_PERMISSION``` only.

But in general you are fine with this idea of changing the UID. So I'm fine that I mod that code a bit to fit my these needs and then we can discuss and find final solution.

**Comment by toras9000** [comment]
Okay, I can think of it as a separate,,,maybe.

Personally, I don't see the benefit in keeping the current image and only adding the ID change.
Other means can be used to do the same or better.
(own image build, derived image build, volume map for startup script)

However, there is no problem even if there is, because if UID/GID is not specified, there is no change from the current situation.
So I applied it to the image for now.
